version: '3.9'

services:
    postgres:
        image: postgres
        container_name: postgres
        restart: on-failure
        environment: 
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        networks: 
            - main
        ports: 
            - "5432:5432"
        volumes: 
            - ./data/postgres:/var/lib/postgresql/data 
            
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: on-failure
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
        ports:
            - "5050:80"
        volumes: 
            - ./data/pgadmin:/var/lib/pgadmin/data
        networks:
            - main
            
    app:
        image: fastapiexample_app
        container_name: app
        restart: on-failure
        command: sh -c "alembic revision --autogenerate -m 'first commit' &&
                        alembic upgrade head &&
                        uvicorn config.main:app --reload --host 0.0.0.0 "
        depends_on: 
            - postgres
        expose: 
            - "8000"
        networks:
            - main
        volumes: 
            - .:/code/

    nginx:
        image: nginx
        container_name: nginx
        command: nginx -g 'daemon off;'
        restart: on-failure
        depends_on:
            - app
        networks: 
            - main
        ports: 
            - "80:80"
        volumes: 
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
          

networks:
  main:

volumes:
  data:
