version: '3.9'

services:
    postgres:
        image: postgres
        container_name: ${DB_HOST}
        restart: on-failure
        environment: 
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        networks: 
            - main
        ports: 
            - "5432:5432"

        deploy:
            resources:
                limits:
                    cpus: 1
                    memory: 1G
                reservations:
                    cpus: 0.50
                    memory: 500M
        volumes: 
            - ./data/postgres:/var/lib/postgresql/data 

networks:
  main:

volumes:
  data: