version: '3.9'

services:
  db:
    image: postgres
    container_name: postgres
    restart: on-failure
    environment: 
      - POSTGRES_DB=blog_db
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
    networks: 
      - main
    ports: 
      - "5432:5432"
    storage_opt:
      size: 1G
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 500M
    volumes: 
      - ./data/postgres:/var/lib/postgresql/data

networks:
  main:

volumes:
  data: